# Generated by Django 5.2.17 on 2026-09-16 17:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=500, unique=True)),
                ('next_allowed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('robots_text', models.TextField(blank=True)),
                ('robots_checked_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('contact_scope', models.CharField(choices=[('person', 'Person'), ('shared', 'Shared business'), ('unknown', 'Unconfirmed')], default='unknown', max_length=16)),
                ('status', models.CharField(choices=[('new', 'Needs review'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected'), ('suppressed', 'Do not contact')], default='new', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_seen', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('url', models.URLField(max_length=1500, unique=True)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('category', models.CharField(choices=[('merchant_services', 'Merchant services'), ('pos', 'Point of sale'), ('payroll', 'Payroll & HR'), ('funding', 'Business funding'), ('telecom', 'Business telecom'), ('it_services', 'IT & managed services'), ('insurance', 'Business insurance'), ('other', 'Other / unclassified')], default='merchant_services', max_length=40)),
                ('active', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('approval_notes', models.TextField(blank=True)),
                ('collector', models.CharField(choices=[('http', 'HTML'), ('browser', 'Browser'), ('demo', 'Demo')], default='http', max_length=12)),
                ('extractor', models.CharField(choices=[('rules', 'CSS / structured HTML'), ('ollama', 'Local Ollama')], default='rules', max_length=12)),
                ('require_sales_role', models.BooleanField(default=True)),
                ('recipe', models.JSONField(blank=True, default=dict)),
                ('allowed_paths', models.TextField(default='/', help_text='One URL path prefix per line. / allows the whole site.')),
                ('follow_links', models.BooleanField(default=True)),
                ('discover_external', models.BooleanField(default=False)),
                ('interval_hours', models.PositiveIntegerField(default=168)),
                ('delay_seconds', models.PositiveIntegerField(default=5)),
                ('max_pages', models.PositiveIntegerField(default=25)),
                ('max_depth', models.PositiveIntegerField(default=2)),
                ('next_due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkerLease',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=64)),
                ('heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('paused', 'Paused'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('pages_done', models.PositiveIntegerField(default=0)),
                ('contacts_seen', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='leads.source')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1500)),
                ('content_hash', models.CharField(max_length=64)),
                ('extraction_signature', models.CharField(max_length=64)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.source')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(max_length=1500)),
                ('facts', models.JSONField(default=dict)),
                ('source_category', models.CharField(choices=[('merchant_services', 'Merchant services'), ('pos', 'Point of sale'), ('payroll', 'Payroll & HR'), ('funding', 'Business funding'), ('telecom', 'Business telecom'), ('it_services', 'IT & managed services'), ('insurance', 'Business insurance'), ('other', 'Other / unclassified')], max_length=40)),
                ('person_tags', models.JSONField(default=list)),
                ('company_tags', models.JSONField(default=list)),
                ('evidence', models.TextField()),
                ('method', models.CharField(default='rules', max_length=20)),
                ('content_hash', models.CharField(max_length=64)),
                ('present', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='leads.lead')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='leads.source')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='SourceCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1500, unique=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('evidence_url', models.URLField(max_length=1500)),
                ('status', models.CharField(choices=[('new', 'Needs review'), ('added', 'Added'), ('dismissed', 'Dismissed')], default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discovered_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.source')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1500)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('message', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='leads.run')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('run', 'url'), name='one_url_per_run')],
            },
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running', 'paused'])), fields=('source',), name='one_open_run_per_source'),
        ),
        migrations.AddConstraint(
            model_name='pagesnapshot',
            constraint=models.UniqueConstraint(fields=('source', 'url'), name='one_page_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(fields=('lead', 'source', 'page_url'), name='one_observation_per_lead_page'),
        ),
    ]
