# Generated by Django 5.2.17 on 2026-09-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='allow_homepage',
            field=models.BooleanField(default=False, help_text='Allow the exact homepage in addition to the path prefixes; does not allow the whole origin.'),
        ),
        migrations.AddField(
            model_name='source',
            name='approval_kind',
            field=models.CharField(choices=[('operator', 'Operator review'), ('policy', 'Campaign policy')], default='operator', max_length=12),
        ),
        migrations.AddField(
            model_name='source',
            name='setup_mode',
            field=models.CharField(choices=[('rules_only', 'Operator-configured rules'), ('automatic', 'Automated recipe setup')], default='rules_only', max_length=16),
        ),
    ]
