# Generated by Django 5.2.17 on 2026-09-24 18:34

import django.db.models.deletion
from django.db import migrations, models

HELD = ("suppressed", "rejected")
LABELS = {"suppressed": "Do not contact", "rejected": "Rejected"}


def backfill(apps, schema_editor):
    """Before this field, only operators changed a lead's status. Existing holds then
    protect unresolved same-name leads already recorded on a shared source page."""
    Lead = apps.get_model("leads", "Lead")
    Observation = apps.get_model("leads", "Observation")
    Lead.objects.exclude(status="new").update(status_origin="operator")
    for held in Lead.objects.filter(status__in=HELD).order_by("pk").iterator():
        for source_id, url in set(Observation.objects.filter(lead=held).values_list("source_id", "page_url")):
            ids = Observation.objects.filter(source_id=source_id, page_url=url).values_list("lead_id", flat=True)
            for other in Lead.objects.filter(pk__in=ids, status="new").exclude(status_origin="operator"):
                if other.name.casefold() != held.name.casefold():
                    continue
                label = LABELS[held.status]
                other.status, other.status_origin, other.held_by = held.status, "hold", held
                other.notes = "\n".join(filter(None, [other.notes, (
                    f"Held as {label}: lead #{held.pk} for this name on {url} was {label.lower()} and its "
                    "identity could not be matched automatically. Review both records before changing this status.")]))
                other.save(update_fields=["status", "status_origin", "held_by", "notes"])


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_source_allow_homepage_source_approval_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='held_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_leads', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status_origin',
            field=models.CharField(choices=[('default', 'Default'), ('operator', 'Operator decision'), ('hold', 'Inherited hold')], default='default', max_length=16),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
