# Generated by Django 5.2.17 on 2026-09-21 19:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discovery', '0002_discoveredurl_dismissal_scope'),
        ('leads', '0002_source_allow_homepage_source_approval_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ControlEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=40)),
                ('reason', models.CharField(max_length=1000)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('succeeded', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JevControl',
            fields=[
                ('key', models.CharField(default='jev', max_length=20, primary_key=True, serialize=False)),
                ('paused', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('allowance_nusd', models.PositiveBigIntegerField(default=1000000000)),
                ('spent_nusd', models.PositiveBigIntegerField(default=0)),
                ('reserved_nusd', models.PositiveBigIntegerField(default=0)),
                ('next_allowed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active_attempt', models.UUIDField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('scope_hash', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(default='pending_domain', max_length=24)),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('max_pages', models.PositiveIntegerField(default=10)),
                ('max_fetches', models.PositiveIntegerField(default=30)),
                ('max_attempts', models.PositiveIntegerField(default=10)),
                ('max_evaluations', models.PositiveIntegerField(default=5)),
                ('fetches', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('processing_seconds', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.company')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='discovery.discoveryrun')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='leads.source')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cache_key', models.CharField(max_length=64, unique=True)),
                ('provider', models.CharField(max_length=10)),
                ('catalog_version', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('actual_model', models.CharField(blank=True, max_length=40)),
                ('request', models.JSONField()),
                ('bindings', models.JSONField(default=dict)),
                ('state', models.CharField(db_index=True, default='queued', max_length=24)),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_token', models.CharField(blank=True, max_length=64)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='classification.company')),
                ('company_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='classification.companyjob')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('url', models.URLField(max_length=1500)),
                ('retrieved_at', models.DateTimeField(null=True)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_hash', models.CharField(max_length=64)),
                ('text_hash', models.CharField(max_length=64)),
                ('scope_hash', models.CharField(max_length=64)),
                ('parser_version', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('links', models.JSONField(default=list)),
                ('truncated', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(null=True)),
                ('provenance', models.CharField(default='fetched', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leads.source')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField()),
                ('cache_hit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uses', to='classification.evaluation')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.evidencedocument')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.evidencedocument'),
        ),
        migrations.CreateModel(
            name='EvidenceSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('text_hash', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=20)),
                ('locator', models.CharField(blank=True, max_length=200)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='classification.evidencedocument')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1500)),
                ('origin', models.CharField(max_length=500)),
                ('state', models.CharField(default='candidate', max_length=20)),
                ('review_note', models.CharField(blank=True, max_length=1000)),
                ('reviewed_by', models.CharField(blank=True, max_length=150)),
                ('verified_at', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='classification.company')),
                ('span', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.evidencespan')),
            ],
        ),
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('probabilities', models.JSONField(default=dict)),
                ('confidence', models.FloatField(null=True)),
                ('evidence_ids', models.JSONField(default=list)),
                ('review_state', models.CharField(default='needs_review', max_length=20)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='judgments', to='classification.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Lineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=1500)),
                ('relation', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineage', to='classification.companyjob')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.evidencedocument')),
                ('evaluation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='classification.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='classification.person'),
        ),
        migrations.CreateModel(
            name='ContactCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=254)),
                ('normalized', models.CharField(max_length=254)),
                ('shared_hint', models.BooleanField(default=False)),
                ('association', models.CharField(default='unknown', max_length=20)),
                ('deliverability', models.CharField(default='not_checked', max_length=20)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classification.company')),
                ('span', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='classification.evidencespan')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classification.person')),
            ],
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='candidate', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliations', to='classification.company')),
                ('span', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.evidencespan')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliations', to='classification.person')),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('active', models.BooleanField(default=False)),
                ('max_companies', models.PositiveIntegerField(default=10)),
                ('max_fetches', models.PositiveIntegerField(default=300)),
                ('max_attempts', models.PositiveIntegerField(default=100)),
                ('fetches', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discovery.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='companyjob',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='classification.pilot'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('day', models.DateField()),
                ('state', models.CharField(default='reserved', max_length=20)),
                ('lease_token', models.CharField(max_length=64)),
                ('request_hash', models.CharField(max_length=64)),
                ('reserved_nusd', models.PositiveBigIntegerField()),
                ('cost_nusd', models.PositiveBigIntegerField(null=True)),
                ('unit_price_nusd', models.PositiveIntegerField(default=42)),
                ('input_tokens', models.PositiveIntegerField(null=True)),
                ('output_tokens', models.PositiveIntegerField(null=True)),
                ('estimated_tokens', models.PositiveIntegerField()),
                ('counter', models.CharField(max_length=200)),
                ('http_status', models.PositiveIntegerField(null=True)),
                ('request_id', models.CharField(blank=True, max_length=200)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('latency_ms', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispatched_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_history', to='classification.evaluation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('evaluation', 'ordinal'), name='one_evaluation_attempt')],
            },
        ),
        migrations.AddConstraint(
            model_name='evidencespan',
            constraint=models.UniqueConstraint(fields=('document', 'key'), name='one_evidence_span_key'),
        ),
        migrations.AddConstraint(
            model_name='evidencespan',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='nonempty_evidence_span'),
        ),
        migrations.AddConstraint(
            model_name='companydomain',
            constraint=models.UniqueConstraint(fields=('company', 'url'), name='one_company_domain_url'),
        ),
        migrations.AddConstraint(
            model_name='judgment',
            constraint=models.UniqueConstraint(fields=('evaluation', 'question_id'), name='one_judgment_question'),
        ),
        migrations.AddConstraint(
            model_name='contactcandidate',
            constraint=models.UniqueConstraint(fields=('span', 'kind', 'value'), name='one_contact_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='affiliation',
            constraint=models.UniqueConstraint(fields=('person', 'company', 'span'), name='one_affiliation_evidence'),
        ),
        migrations.AddConstraint(
            model_name='companyjob',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ('pending_domain', 'pending_approval', 'queued', 'discovering', 'classifying', 'paused', 'needs_recipe_review'))), fields=('key',), name='one_active_company_scope'),
        ),
    ]
