# Generated by Django 5.2.17 on 2026-09-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencedocument',
            name='extraction_signature',
            field=models.CharField(default='', max_length=64),
        ),
    ]
