# Generated by Django 5.2.17 on 2026-09-21 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_evidencedocument_extraction_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationuse',
            name='company_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='classification.companyjob'),
        ),
    ]
