# Generated by Django 5.2.17 on 2026-09-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0004_evaluationuse_company_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jevcontrol',
            name='cumulative_attempt_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
