# Generated by Django 5.2.17 on 2026-09-16 22:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discovery', '0002_discoveredurl_dismissal_scope'),
        ('leads', '0002_source_allow_homepage_source_approval_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discovery.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('generation', models.PositiveIntegerField()),
                ('status', models.CharField(default='candidate', max_length=16)),
                ('recipe', models.JSONField(default=dict)),
                ('validation', models.JSONField(default=dict)),
                ('score', models.PositiveIntegerField(default=0)),
                ('scope_hash', models.CharField(max_length=64)),
                ('probe_version', models.CharField(default='1.0', max_length=20)),
                ('created_by', models.CharField(default='deterministic worker', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_versions', to='leads.source')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='SiteAutomationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('probe_queued', 'Probe Queued'), ('probing', 'Probing'), ('probe_complete', 'Probe Complete'), ('recipe_queued', 'Recipe Queued'), ('recipe_testing', 'Recipe Testing'), ('recipe_ready', 'Recipe Ready'), ('recipe_released', 'Recipe Released'), ('canary', 'Canary'), ('active', 'Active'), ('paused', 'Paused'), ('failed', 'Failed')], default='probe_queued', max_length=24)),
                ('policy_snapshot', models.JSONField(default=dict)),
                ('scope_hash', models.CharField(max_length=64)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('recon', models.JSONField(default=dict)),
                ('processing', models.BooleanField(default=False)),
                ('lease_token', models.CharField(blank=True, max_length=64)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('next_probe_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_jobs', to='discovery.campaign')),
                ('current_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_jobs', to='automation.recipeversion')),
                ('last_good_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='healthy_jobs', to='automation.recipeversion')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automation_job', to='leads.source')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='automation.siteautomationjob'),
        ),
        migrations.CreateModel(
            name='ProbePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField(default=1)),
                ('phase', models.CharField(default='probe', max_length=10)),
                ('url', models.URLField(max_length=1500)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='queued', max_length=12)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('private_key', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='automation.siteautomationjob')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AutomationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=24)),
                ('message', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='automation.siteautomationjob')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SitePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('min_url_score', models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(100)])),
                ('min_recipe_score', models.PositiveIntegerField(default=85, validators=[django.core.validators.MinValueValidator(85), django.core.validators.MaxValueValidator(90)])),
                ('allowed_paths', models.TextField(default='/team\n/our-team\n/staff\n/people\n/sales\n/agents\n/representatives\n/reps\n/partners\n/contact\n/contact-us\n/about\n/about-us\n/executive-team\n/leadership\n/independent-sales', max_length=3000)),
                ('allow_homepage', models.BooleanField(default=True)),
                ('denied_domains', models.TextField(default='facebook.com\nlinkedin.com\nx.com\ntwitter.com\ninstagram.com\ntiktok.com\nyoutube.com\nreddit.com', max_length=3000)),
                ('max_sites_per_day', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)])),
                ('probe_pages', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('canary_pages', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('delay_seconds', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(3600)])),
                ('recheck_days', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('notes', models.TextField(blank=True, max_length=3000)),
                ('pending_scan_cursor', models.PositiveBigIntegerField(default=0, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_policy', to='discovery.campaign')),
            ],
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.UniqueConstraint(fields=('source', 'version'), name='one_recipe_version_per_source'),
        ),
        migrations.AddConstraint(
            model_name='probepage',
            constraint=models.UniqueConstraint(fields=('job', 'generation', 'phase', 'url'), name='one_probe_page_per_generation'),
        ),
    ]
