# Generated by Django 5.2.17 on 2026-09-21 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteautomationjob',
            name='company_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classification.companyjob'),
        ),
    ]
