# Generated by Django 5.2.17 on 2026-09-16 20:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('merchant_services', 'Merchant services'), ('pos', 'Point of sale'), ('payroll', 'Payroll & HR'), ('funding', 'Business funding'), ('telecom', 'Business telecom'), ('it_services', 'IT & managed services'), ('insurance', 'Business insurance'), ('other', 'Other / unclassified')], default='merchant_services', max_length=40)),
                ('keywords', models.TextField(default='merchant services\npayment processing\npoint of sale\nPOS reseller', max_length=3000)),
                ('sales_terms', models.TextField(default='sales\nrepresentative\nagent\nreseller\nconsultant\npartner', max_length=3000)),
                ('exclusions', models.TextField(blank=True, max_length=3000)),
                ('region', models.CharField(blank=True, max_length=160)),
                ('use_sitemaps', models.BooleanField(default=True)),
                ('max_pages', models.PositiveIntegerField(default=50, help_text='Maximum page and sitemap jobs in each run.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('max_depth', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('max_candidates', models.PositiveIntegerField(default=1000, help_text='Maximum saved URLs in this campaign, including reviewed URLs.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10000)])),
                ('max_new_domains', models.PositiveIntegerField(default=25, help_text='Maximum previously unseen origins discovered in each run.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('daily_requests', models.PositiveIntegerField(default=200, help_text='Fetch attempts per UTC day, including robots checks and retries. Redirect hops are separately bounded.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)])),
                ('min_score', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('interval_hours', models.PositiveIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8760)])),
                ('search_enabled', models.BooleanField(default=False)),
                ('search_queries', models.TextField(blank=True, help_text='One exact search query per line, up to 10. Include a location here to target it in search.', max_length=6000)),
                ('daily_search_limit', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField(default=False)),
                ('next_due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sources', models.ManyToManyField(blank=True, related_name='discovery_campaigns', to='leads.source')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1500)),
                ('origin', models.CharField(db_index=True, max_length=500)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('context', models.CharField(blank=True, max_length=600)),
                ('found_on', models.URLField(blank=True, max_length=1500)),
                ('method', models.CharField(default='link', max_length=20)),
                ('kind', models.CharField(choices=[('page', 'Page'), ('sitemap', 'Sitemap')], default='page', max_length=10)),
                ('search_query', models.CharField(blank=True, max_length=600)),
                ('score', models.IntegerField(default=0)),
                ('reasons', models.JSONField(default=list)),
                ('decision', models.CharField(choices=[('pending', 'Needs review'), ('approved', 'Approved scope'), ('dismissed', 'Dismissed')], default='pending', max_length=16)),
                ('last_result', models.CharField(blank=True, max_length=1000)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='discovery.campaign')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_urls', to='leads.source')),
            ],
            options={
                'ordering': ['-score', '-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='queued', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_tick_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('pages_done', models.PositiveIntegerField(default=0)),
                ('contacts_seen', models.PositiveIntegerField(default=0)),
                ('new_contacts', models.PositiveIntegerField(default=0)),
                ('candidates_found', models.PositiveIntegerField(default=0)),
                ('new_domains', models.PositiveIntegerField(default=0)),
                ('duplicates_seen', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='discovery.campaign')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('page', 'Page'), ('sitemap', 'Sitemap'), ('search', 'Search')], default='page', max_length=10)),
                ('url', models.CharField(max_length=1500)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('contacts_seen', models.PositiveIntegerField(default=0)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='discovery.discoveredurl')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.source')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='discovery.discoveryrun')),
            ],
            options={
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.AddField(
            model_name='discoveredurl',
            name='first_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_urls', to='discovery.discoveryrun'),
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('requests', models.PositiveIntegerField(default=0)),
                ('searches', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='discovery.campaign')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign', 'day'), name='one_discovery_daily_usage')],
            },
        ),
        migrations.AddConstraint(
            model_name='discoveryrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running', 'paused'])), fields=('campaign',), name='one_open_discovery_run'),
        ),
        migrations.AddConstraint(
            model_name='discoveryjob',
            constraint=models.UniqueConstraint(fields=('run', 'kind', 'url'), name='one_discovery_job'),
        ),
        migrations.AddConstraint(
            model_name='discoveredurl',
            constraint=models.UniqueConstraint(fields=('campaign', 'url'), name='one_url_per_campaign'),
        ),
    ]
