# Generated by Django 5.2.17 on 2026-09-16 22:43

from django.db import migrations, models

def preserve_dismissals(apps, schema_editor):
    # Old records did not distinguish a filter from an operator dismissal.
    # Preserve them conservatively; a policy must not silently undo a past decision.
    apps.get_model('discovery', 'DiscoveredURL').objects.filter(decision='dismissed').update(dismissal_scope='origin')


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveredurl',
            name='dismissal_scope',
            field=models.CharField(blank=True, choices=[('', 'Automatic filter / none'), ('url', 'Operator URL dismissal'), ('origin', 'Operator origin dismissal')], default='', max_length=8),
        ),
        migrations.RunPython(preserve_dismissals, migrations.RunPython.noop),
    ]
