# Generated by Django 5.2.17 on 2026-09-21 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
        ('discovery', '0002_discoveredurl_dismissal_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveredurl',
            name='manual_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoveryjob',
            name='company_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classification.companyjob'),
        ),
    ]
