# Generated by Django 5.2.17 on 2026-09-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_discoveredurl_manual_review_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveryjob',
            name='new_contacts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
